//
//  ADSBXResponse.swift
//  HMD
//
//  Created by Yi JIANG on 11/6/17.
//  Copyright © 2017 RobertYiJiang. All rights reserved.
//

// This file was generated by json2swift. https://github.com/ijoshsmith/json2swift

import Foundation

//
// MARK: - Data Model
//
struct ADSBXResponse { // TODO: Rename this struct
    var listVersionId: String?
    var totalAircraft: Int?
    var totalSource: Int?
    var hasSilhouettes: Bool?
    var hasOperator: Bool?
    var hasPictures: Bool?
    var pixelWidth: Int?
    var pixelHeight: Int?
    var shortTrailSec: Int?
    var timeStamp: Int?
    var aircraftList: [ADSBAircraft]?
    var feedList: [ADSBFeeds]?
    var feedId: Int?
    var hasConfigChanged: Bool?
    
    init?(responseDict: [String: Any]) {
        listVersionId  = responseDict[ExRspKeys.ListVersionId] as? String
        totalAircraft = responseDict[ExRspKeys.TotalAircraft] as? Int
        totalSource     = responseDict[ExRspKeys.TotalSource] as? Int
        hasSilhouettes = responseDict[ExRspKeys.HasSilhouettes] as? Bool
        hasOperator = responseDict[ExRspKeys.HasOperator] as? Bool
        hasPictures = responseDict[ExRspKeys.HasPictures] as? Bool
        pixelWidth    = responseDict[ExRspKeys.PixelWidth] as? Int
        pixelHeight    = responseDict[ExRspKeys.PixelHeight] as? Int
        shortTrailSec = responseDict[ExRspKeys.ShortTrailSec] as? Int
        timeStamp     = responseDict[ExRspKeys.TimeStamp] as? Int
        aircraftList  = ADSBAircraft.fromDictArray(responseDict[ExRspKeys.AircraftList] as! [[String: Any]])
        feedList   = ADSBFeeds.fromDictionaryArray(responseDict[ExRspKeys.FeedList] as! [[String: Any]])
        feedId = responseDict[ExRspKeys.FeedId] as? Int
        hasConfigChanged = responseDict[ExRspKeys.HasConfigChanged] as? Bool
    }
}

struct ADSBFeeds { // TODO: Rename this struct
    var id: Int?
    var name: String?
    var polarPlot: Bool?
    
    static func fromDictionaryArray(_ feedArray: [[String: Any]]) -> [ADSBFeeds] {
        var models:[ADSBFeeds] = []
        for feed in feedArray
        {
            models.append(ADSBFeeds.init(withDictionary: feed)!)
        }
        return models
    }
    
    init?(withDictionary feedDict: [String: Any]) {
        id = feedDict["id"] as? Int
        name = feedDict["name"] as? String
        polarPlot = feedDict["polarPlot"] as? Bool
    }
}
