//
//  ADSBAerodrome.swift
//  HMD
//
//  Created by Yi JIANG on 11/6/17.
//  Copyright © 2017 RobertYiJiang. All rights reserved.
//

import Foundation

// This file was generated by json2swift. https://github.com/ijoshsmith/json2swift

import Foundation

//
// MARK: - Data Model
//
struct Flight: CreatableFromJSON { // TODO: Rename this struct
    let altT: Int
    let bad: Bool
    let brng: Double
    let cMsgs: Int
    let cNum: String
    let call: String
    let callSus: Bool
    let cou: String
    let dst: Double
    let engMount: Int
    let engType: Int
    let engines: String
    let fSeen: String
    let flightsCount: Int
    let gnd: Bool
    let hasPic: Bool
    let hasSig: Bool
    let help: Bool
    let icao: String
    let id: Int
    let inHg: Double
    let interested: Bool
    let lat: Double
    let long: Double
    let man: String
    let mdl: String
    let mil: Bool
    let mlat: Bool
    let op: String
    let opIcao: String
    let posTime: Int
    let rcvr: Int
    let reg: String
    let spd: Int
    let spdTyp: Int
    let species: Int
    let sqk: String
    let tSecs: Int
    let tisb: Bool
    let trkH: Bool
    let trt: Int
    let type: String
    let vsiT: Int
    let wTC: Int
    let year: String
    init(json: [String: Any]) {
        altT      = json["AltT"] as? Int
        bad       = json["Bad"] as? Bool
        brng      = Double(json: json, key: "Brng")
        cMsgs     = json["CMsgs"] as? Int
        cNum      = json["CNum"] as? String
        call      = json["Call"] as? String
        callSus   = json["CallSus"] as? Bool
        cou       = json["Cou"] as? String
        dst       = Double(json: json, key: "Dst")
        engMount  = json["EngMount"] as? Int
        engType   = json["EngType"] as? Int
        engines   = json["Engines"] as? String
        fSeen     = json["FSeen"] as? String
        flightsCount = json["FlightsCount"] as? Int
        gnd       = json["Gnd"] as? Bool
        hasPic    = json["HasPic"] as? Bool
        hasSig    = json["HasSig"] as? Bool
        help      = json["Help"] as? Bool
        icao      = json["Icao"] as? String
        id        = json["Id"] as? Int
        inHg      = Double(json: json, key: "InHg")
        interested = json["Interested"] as? Bool
        lat       = Double(json: json, key: "Lat")
        long      = Double(json: json, key: "Long")
        man       = json["Man"] as? String
        mdl       = json["Mdl"] as? String
        mil       = json["Mil"] as? Bool
        mlat      = json["Mlat"] as? Bool
        op        = json["Op"] as? String
        opIcao    = json["OpIcao"] as? String
        posTime   = json["PosTime"] as? Int
        rcvr      = json["Rcvr"] as? Int
        reg       = json["Reg"] as? String
        spd       = json["Spd"] as? Int
        spdTyp    = json["SpdTyp"] as? Int
        species   = json["Species"] as? Int
        sqk       = json["Sqk"] as? String
        tSecs     = json["TSecs"] as? Int
        tisb      = json["Tisb"] as? Bool
        trkH      = json["TrkH"] as? Bool
        trt       = json["Trt"] as? Int
        type      = json["Type"] as? String
        vsiT      = json["VsiT"] as? Int
        wTC       = json["WTC"] as? Int
        year      = json["Year"] as? String
    }
}

